item {
    id: 1
    name: 'Serafino'
}
item {
    id: 2
    name: 'FrancescoTordo'
}
item {
    id: 3
    name: 'FrancescoFerraguzzi'
}
item {
    id: 4
    name: 'Martina'
}
item {
    id: 5
    name: 'FrancescoRe'
}
item {
    id: 6
    name: 'Elia'
}
item {
    id: 7
    name: 'Valeria'
}
item {
    id: 8
    name: 'Federico'
}
item {
    id: 9
    name: 'Dario'
}